/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {

        // ===================================================
        // THÈME GYM — dark theme (préfixe: gym-)
        // Utilisé dans Login.vue, Register.vue, HomeView.vue
        // ===================================================
        'gym-primary': '#69daff',
        'gym-primary-dim': '#00c0ea',
        'gym-primary-fixed': '#00cffc',
        'gym-primary-fixed-dim': '#00c0ea',
        'gym-primary-container': '#00cffc',
        'gym-on-primary': '#004a5d',
        'gym-on-primary-fixed': '#002a35',
        'gym-on-primary-fixed-variant': '#004a5c',
        'gym-on-primary-container': '#004050',
        'gym-secondary': '#bf81ff',
        'gym-secondary-dim': '#9c42f4',
        'gym-secondary-fixed': '#e4c6ff',
        'gym-secondary-fixed-dim': '#dab4ff',
        'gym-secondary-container': '#7701d0',
        'gym-on-secondary': '#32005c',
        'gym-on-secondary-fixed': '#4e008a',
        'gym-on-secondary-fixed-variant': '#7500cc',
        'gym-on-secondary-container': '#f0dcff',
        'gym-tertiary': '#ff7346',
        'gym-tertiary-dim': '#ff7346',
        'gym-tertiary-fixed': '#ff9473',
        'gym-tertiary-fixed-dim': '#ff7d54',
        'gym-tertiary-container': '#fc4c00',
        'gym-on-tertiary': '#420d00',
        'gym-on-tertiary-fixed': '#340800',
        'gym-on-tertiary-fixed-variant': '#6e1c00',
        'gym-on-tertiary-container': '#0e0100',
        'gym-surface': '#0c0e12',
        'gym-surface-dim': '#0c0e12',
        'gym-surface-bright': '#292c32',
        'gym-surface-variant': '#23262c',
        'gym-surface-tint': '#69daff',
        'gym-surface-lowest': '#000000',
        'gym-surface-low': '#111318',
        'gym-surface-container': '#171a1f',
        'gym-surface-high': '#1d2025',
        'gym-surface-highest': '#23262c',
        'gym-on-surface': '#f6f6fc',
        'gym-on-surface-variant': '#aaabb0',
        'gym-on-background': '#f6f6fc',
        'gym-background': '#0c0e12',
        'gym-inverse-surface': '#f9f9ff',
        'gym-inverse-on-surface': '#53555a',
        'gym-inverse-primary': '#006880',
        'gym-outline': '#74757a',
        'gym-outline-variant': '#46484d',
        'gym-error': '#ff716c',
        'gym-error-dim': '#d7383b',
        'gym-error-container': '#9f0519',
        'gym-on-error': '#490006',
        'gym-on-error-container': '#ffa8a3',

        // ===================================================
        // THÈME ADMIN — light theme (préfixe: adm-)
        // Utilisé dans AppLayout.vue, Dashboard.vue, etc.
        // ===================================================
        'adm-surface-lowest': '#ffffff',
        'adm-surface-low': '#f2f3ff',
        'adm-surface-container': '#eaedff',
        'adm-surface-high': '#e2e7ff',
        'adm-surface-highest': '#dae2fd',
        'adm-surface': '#faf8ff',
        'adm-surface-dim': '#d2d9f4',
        'adm-surface-bright': '#faf8ff',
        'adm-surface-variant': '#dae2fd',
        'adm-on-surface': '#131b2e',
        'adm-on-surface-variant': '#464554',
        'adm-on-background': '#131b2e',
        'adm-background': '#faf8ff',
        'adm-primary': '#4648d4',
        'adm-primary-fixed': '#e1e0ff',
        'adm-primary-fixed-dim': '#c0c1ff',
        'adm-primary-container': '#6063ee',
        'adm-on-primary': '#ffffff',
        'adm-on-primary-fixed': '#07006c',
        'adm-on-primary-fixed-variant': '#2f2ebe',
        'adm-on-primary-container': '#fffbff',
        'adm-secondary': '#006e2f',
        'adm-secondary-container': '#6bff8f',
        'adm-secondary-fixed': '#6bff8f',
        'adm-secondary-fixed-dim': '#4ae176',
        'adm-on-secondary': '#ffffff',
        'adm-on-secondary-fixed': '#002109',
        'adm-on-secondary-fixed-variant': '#005321',
        'adm-on-secondary-container': '#007432',
        'adm-tertiary': '#b61722',
        'adm-tertiary-container': '#da3437',
        'adm-tertiary-fixed': '#ffdad7',
        'adm-tertiary-fixed-dim': '#ffb3ad',
        'adm-on-tertiary': '#ffffff',
        'adm-on-tertiary-fixed': '#410004',
        'adm-on-tertiary-fixed-variant': '#930013',
        'adm-on-tertiary-container': '#fffbff',
        'adm-error': '#ba1a1a',
        'adm-error-container': '#ffdad6',
        'adm-on-error': '#ffffff',
        'adm-on-error-container': '#93000a',
        'adm-outline': '#767586',
        'adm-outline-variant': '#c7c4d7',
        'adm-inverse-surface': '#283044',
        'adm-inverse-primary': '#c0c1ff',
        'adm-inverse-on-surface': '#eef0ff',
        'adm-surface-tint': '#494bd6',
      },
      fontFamily: {
        headline: ['Lexend', 'Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}